### ISSUE TITLE
sphinx autodoc inspection error on JSONField

### ISSUE THREAD

**Issue by rlskoeser** [dmkoch/django-jsonfield#160]
I'm getting an error trying to generate sphinx docs.  It seems that sphinx is unable to inspect JSONField.

```
Traceback (most recent call last):
  File "/Users/rsutton/workarea/env/readux/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 393, in import_object
    obj = self.get_attr(obj, part)
  File "/Users/rsutton/workarea/env/readux/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 289, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/Users/rsutton/workarea/env/readux/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
```

**Comment by robmosca** [comment]
I also get the same error.

**Comment by dmkoch** [comment]
Can you post a script help me reproduce the error?

**Comment by dmkoch** [comment]
Please reopen if this is still an issue
